apiVersion: v1
kind: Service
metadata:
    name: philosophy
    labels:
        role: philosophy
spec:
    type: LoadBalancer
    ports:
        - port: 4000
          targetPort: 5000
    selector:
        role: philosophy

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: philosophy
    labels:
        role: philosophy
spec:
    selector:
        matchLabels:
            role: philosophy
    replicas: 1
    template:
        metadata:
            labels:
                role: philosophy
        spec:
            containers:
                - name: philosphy
                  image: phil:1.0
                  env:
                      - name: PORT
                        value: "5000"
                  ports:
                      - containerPort: 5000
